import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/cardcomponent/Header";
import Navbar from "../Components/Navbar";

export default function Home() {
  return (
    <div style={{ background: "black" }}>
      <Head>
        <title>E-Summit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossOrigin="anonymous"
        />
      </Head>
      <Navbar />
      <Header />
      <Footer />
    </div>
  );
}
